/* Racing fleet — full specification data */
window.RACING_CARS_DATA = [
  {
    id: 'f1-x1', name: 'Teevra F1-X1', category: 'f1', badge: 'Formula 1',
    image: 'assets/cars/f1racer1.avif',
    hp: 1050, speed: 380, accel: 2.1, torque: 850, weight: 798,
    engine: '1.6L Hybrid Turbo V6', drivetrain: 'RWD', transmission: '8-Speed Seamless Shift', fuel: 'Hybrid (E10 + MGU-K)',
    desc: 'Open-wheel Formula 1 challenger with active aero, hybrid energy recovery, and 15,000 RPM redline for qualifying dominance.',
    pedigree: '2026 Teevra Works Team · FIA Formula 1 spec · 24 race season',
    highlights: ['FIA homologated hybrid PU', '900 kg downforce @ 300 km/h', 'Sub-2.2s race launch', 'DRS + active floor', 'Pirelli compound strategy ready'],
    performance: { power: 98, speed: 95, handling: 94, aero: 97, braking: 92, acceleration: 96, durability: 78, efficiency: 82 },
    engineSpecs: {
      layout: '90° V6 Twin Turbo + ERS', displacement: '1,600 cc', cylinders: '6',
      compression: '13.0:1', turbo: 'Twin-scroll + MGU-H', redline: '15,000 RPM',
      powerOutput: '1,050 HP (combined)', torquePeak: '850 Nm @ 8,500 RPM',
      fuelSystem: 'Direct injection 500 bar', cooling: 'Triple intercooler + oil-to-water',
      hybridSystem: 'MGU-K 120kW / MGU-H 95% recovery', emissions: 'FIA fuel-flow regulated',
    },
    chassisSpecs: {
      frame: 'Carbon fiber monocoque + halo', length: '5,500 mm', width: '2,000 mm',
      height: '950 mm', wheelbase: '3,600 mm', trackF: '1,650 mm', trackR: '1,580 mm',
      suspension: 'Push-rod double wishbone', dampers: 'Four-way adjustable Öhlins',
      brakes: 'Carbon-carbon 380 mm / 6-piston', tires: 'Pirelli C5 Slick 305/670-R13',
      aero: 'DRS rear wing + underfloor tunnels', weightDist: '42% front / 58% rear',
      fuelTank: '110 L · ~305 km race range', safety: 'Halo FIA 8869 + HANS + biometric',
    },
    featuresDetailed: [
      { name: 'DRS Rear Wing', desc: 'Drag Reduction System opens on straights for +15 km/h top speed when within 1s of car ahead.' },
      { name: 'Hybrid MGU-K Boost', desc: '120 kW electric motor delivers instant 160 Nm torque fill out of slow corners.' },
      { name: 'Carbon Monocoque', desc: 'Pre-preg carbon survival cell tested to 60G lateral impact FIA standard.' },
      { name: 'Active Floor Aero', desc: 'Ride-height-sensitive underfloor generates 900 kg downforce at 300 km/h.' },
      { name: 'Live Telemetry', desc: '300+ sensors stream real-time data to pit wall for strategy and setup changes.' },
      { name: 'Pit Lane Limiter', desc: 'GPS-linked speed cap with automatic engagement entering pit entry line.' },
      { name: 'Brake-by-Wire Rear', desc: 'Electronic rear brake bias adjusts per corner via steering and pedal map.' },
      { name: 'Energy Store Mode', desc: 'Deploy / harvest toggle for qualifying lap or race fuel-save phases.' },
    ],
    technology: [
      { name: 'MGU-H Turbo Compounding', desc: 'Recovers exhaust energy to spool turbo and eliminate lag below 12,000 RPM.' },
      { name: 'Semi-Auto Seamless Shift', desc: '8-speed box shifts in 40 ms with zero torque interruption.' },
      { name: 'Biometric Driver Monitor', desc: 'Helmet-linked heart rate and G-force logging for safety alerts.' },
      { name: 'Predictive Tire Model', desc: 'AI estimates grip loss 3 laps ahead based on deg and track temp.' },
      { name: 'Overcut Strategy HUD', desc: 'Real-time delta display for undercut/overcut pit window decisions.' },
    ],
    accel200: 4.6, quarterMile: 9.1,
  },
  {
    id: 'thunder-gt', name: 'Thunder GT-R', category: 'gt', badge: 'GT Racing',
    image: 'assets/cars/model-gt.jpg',
    hp: 720, speed: 340, accel: 2.8, torque: 780, weight: 1420,
    engine: '4.0L Twin-Turbo V8', drivetrain: 'RWD', transmission: '7-Speed Dual-Clutch', fuel: 'Race Fuel 102 RON',
    desc: 'GT3 sprint racer with widebody aero, roll cage, and 720 HP twin-turbo V8 built for 3-hour endurance heats.',
    pedigree: 'Teevra GT Division · SRO GT3 Balance of Performance · 2026 season spec',
    highlights: ['GT3 BOP 1,420 kg', '1.8G lateral grip', '80 ms shift time', '24-hour gearbox rated', 'Air jack pit ready'],
    performance: { power: 88, speed: 86, handling: 90, aero: 82, braking: 88, acceleration: 85, durability: 88, efficiency: 72 },
    engineSpecs: {
      layout: '90° V8 Twin Turbo', displacement: '3,996 cc', cylinders: '8',
      compression: '9.5:1', turbo: 'Twin Garrett GT2860RS', redline: '7,500 RPM',
      powerOutput: '720 HP @ 6,800 RPM', torquePeak: '780 Nm @ 4,500 RPM',
      fuelSystem: 'Port + direct injection', cooling: 'Dual radiator + oil cooler',
      hybridSystem: 'None (ICE only)', emissions: 'Race catalytic bypass',
    },
    chassisSpecs: {
      frame: 'Steel roll cage + aluminum monocoque', length: '4,650 mm', width: '2,050 mm',
      height: '1,280 mm', wheelbase: '2,720 mm', trackF: '1,680 mm', trackR: '1,620 mm',
      suspension: 'Double wishbone + coilover', dampers: 'Three-way adjustable KW',
      brakes: 'Carbon ceramic 400 mm / 6-piston', tires: 'Michelin S9L Slick 300/680-R18',
      aero: 'Adjustable rear wing + splitter', weightDist: '48% front / 52% rear',
      fuelTank: '120 L · ~450 km stint', safety: 'FIA GT3 roll cage + fire suppression',
    },
    featuresDetailed: [
      { name: 'FIA Roll Cage', desc: 'T45 steel cage with door bars and roof intrusion protection homologated to GT3 spec.' },
      { name: 'Adjustable Rear Wing', desc: '6-angle wing setting from max downforce to low-drag Le Mans configuration.' },
      { name: 'Launch Control', desc: 'Clutch-slip map holds 5,500 RPM for consistent standing start off the line.' },
      { name: 'Carbon Ceramic Brakes', desc: '400 mm rotors withstand 900°C without fade over 45-minute stints.' },
      { name: 'Motec Data Logger', desc: 'Records 50 channels at 100 Hz including tire pressure and brake temps.' },
      { name: 'Nitrogen Suspension', desc: 'Pressurized damper reservoirs maintain consistent ride height under load.' },
      { name: 'Quick-Release Steering', desc: 'Sparco wheel with multi-function display and paddle shift integration.' },
      { name: 'Air Jack System', desc: 'Four-corner pneumatic jacks lift car in 3 seconds for sub-60s pit stops.' },
    ],
    technology: [
      { name: 'Traction Control Maps', desc: '12-position dial adjusts slip percentage from wet to dry setup.' },
      { name: 'ABS Corner Profile', desc: 'Sector-based ABS intervention tuned per track corner type.' },
      { name: 'Pit Stop Timer Link', desc: 'Wheel gun sensor syncs with crew radio for stop-go penalty avoidance.' },
      { name: 'Tire Pressure RF Monitor', desc: 'Bluetooth sensors alert pit when PSI drops below stint threshold.' },
    ],
    accel200: 8.4, quarterMile: 10.6,
  },
  {
    id: 'apex-gt3', name: 'Apex GT3', category: 'gt', badge: 'GT Racing',
    image: 'assets/cars/gt-porsche.jpg',
    hp: 680, speed: 320, accel: 3.0, torque: 710, weight: 1280,
    engine: '4.2L Flat-Six NA', drivetrain: 'RWD', transmission: '6-Speed Sequential', fuel: 'Race Fuel 102 RON',
    desc: 'Naturally aspirated flat-six GT3 with razor-sharp throttle response and 24-hour Nürburgring proven reliability.',
    pedigree: 'Apex Motorsport · Porsche GT3 Customer Racing · N24 class winner platform',
    highlights: ['Flat-six 680 HP NA', '1,280 kg dry weight', '24h Nürburgring proven', 'Center-lock pit stops', 'Low CoG chassis'],
    performance: { power: 84, speed: 82, handling: 93, aero: 85, braking: 90, acceleration: 82, durability: 92, efficiency: 74 },
    engineSpecs: {
      layout: 'Flat-6 Naturally Aspirated', displacement: '4,194 cc', cylinders: '6',
      compression: '12.5:1', turbo: 'None', redline: '8,800 RPM',
      powerOutput: '680 HP @ 8,200 RPM', torquePeak: '710 Nm @ 6,800 RPM',
      fuelSystem: 'Individual throttle bodies', cooling: 'Front + side pod radiators',
      hybridSystem: 'None', emissions: 'Race spec exhaust',
    },
    chassisSpecs: {
      frame: 'Aluminum-steel spaceframe', length: '4,580 mm', width: '2,040 mm',
      height: '1,260 mm', wheelbase: '2,650 mm', trackF: '1,640 mm', trackR: '1,600 mm',
      suspension: 'MacPherson strut front / multi-link rear', dampers: 'Bilstein racing coilover',
      brakes: 'Steel ventilated 380 mm / 4-piston', tires: 'Pirelli GT3 DH 315/680-R18',
      aero: 'Carbon splitter + swan-neck wing', weightDist: '45% front / 55% rear',
      fuelTank: '100 L · ~380 km stint', safety: 'FIA GT3 spec fuel cell + extinguisher',
    },
    featuresDetailed: [
      { name: 'Carbon Front Splitter', desc: 'Adjustable splitter generates 180 kg front downforce at 200 km/h.' },
      { name: 'Rear Diffuser', desc: 'Venturi diffuser works with wing for balanced aero platform.' },
      { name: 'ABS Map Selector', desc: 'Dry / damp / wet ABS curves selectable from steering wheel.' },
      { name: 'Driver Cooling Duct', desc: 'Helmet and seat ducts maintain core temp during 2-hour stints.' },
      { name: 'Center-Lock Wheels', desc: 'Single-nut wheels reduce pit stop time by 1.2 seconds per corner.' },
      { name: 'Fuel Cell Safety Bladder', desc: 'FIA FT3 certified cell prevents leak in 30G impact.' },
      { name: 'Sequential Shift Cut', desc: 'Ignition cut on upshift completes changes in 90 ms flat.' },
      { name: 'Night Racing Lights', desc: 'LED headlight kit meets LMGT3 night visibility rules.' },
    ],
    technology: [
      { name: 'Flat-Six Gyro Effect', desc: 'Low engine height enables 35 mm lower CoG vs V8 rivals.' },
      { name: 'Torque Vectoring Diff', desc: 'Mechanical LSD with preload adjust for trail-brake rotation.' },
      { name: 'Stint Fuel Calculator', desc: 'Dash shows laps remaining based on real-time consumption.' },
      { name: 'Vibration Harmonic Damper', desc: 'Engine mount tuning reduces fatigue on long straights.' },
    ],
    accel200: 9.2, quarterMile: 11.0,
  },
  {
    id: 'rally-wrc', name: 'Rally Beast WRC', category: 'rally', badge: 'Rally Cross',
    image: 'assets/cars/rally.jpg',
    hp: 580, speed: 260, accel: 3.4, torque: 650, weight: 1260,
    engine: '2.0L Turbo I4', drivetrain: 'AWD', transmission: '5-Speed Sequential', fuel: 'E85 Ethanol',
    desc: 'WRC-spec rally car with 350 mm clearance, anti-lag turbo, and active center diff for any surface.',
    pedigree: 'Teevra Rally Works · WRC Rally1 hybrid era spec · Monte Carlo ready',
    highlights: ['350 mm ground clearance', 'Anti-lag turbo', 'Hydraulic handbrake', 'Gravel / snow / tarmac maps', 'AWD torque split'],
    performance: { power: 78, speed: 72, handling: 88, aero: 65, braking: 80, acceleration: 80, durability: 90, efficiency: 68 },
    engineSpecs: {
      layout: 'Inline-4 Turbo + anti-lag', displacement: '1,998 cc', cylinders: '4',
      compression: '8.8:1', turbo: 'Garrett G25-660 + ALS', redline: '7,000 RPM',
      powerOutput: '580 HP @ 6,200 RPM', torquePeak: '650 Nm @ 4,000 RPM',
      fuelSystem: 'Port injection E85', cooling: 'Roof scoop + intercooler',
      hybridSystem: 'Rally1 spec 100 kW (optional)', emissions: 'E85 renewable fuel',
    },
    chassisSpecs: {
      frame: 'Welded roll cage + tubular subframes', length: '4,200 mm', width: '1,870 mm',
      height: '1,420 mm', wheelbase: '2,550 mm', trackF: '1,620 mm', trackR: '1,620 mm',
      suspension: 'Long-travel MacPherson + hydraulic bump stops', dampers: 'Reiger 4-way rally',
      brakes: 'Aluminum 355 mm / water-cooled', tires: 'Pirelli Sottozero / Scorpion WRC',
      aero: 'Minimal — roof vent + rear wing', weightDist: '50% front / 50% rear',
      fuelTank: '80 L · ~220 km special stage', safety: 'FIA rally roll cage + medical kit',
    },
    featuresDetailed: [
      { name: 'Active Center Diff', desc: 'Electronically controlled split from 50/50 to 30/70 rear bias in milliseconds.' },
      { name: 'Hydraulic Handbrake', desc: 'Rear axle lock for Scandinavian flicks and hairpin rotation.' },
      { name: 'Long-Travel Suspension', desc: '280 mm wheel travel absorbs jumps without bottoming on landing.' },
      { name: 'Skid Plates', desc: 'Kevlar-reinforced underbody protects sump and gearbox on rocky stages.' },
      { name: 'Co-Driver Intercom', desc: 'Noise-cancelled headset with pace note recorder integration.' },
      { name: 'Anti-Lag Turbo', desc: 'Exhaust bypass keeps turbo spooled between shifts on loose surfaces.' },
      { name: 'Gravel / Tarmac Maps', desc: 'ECU switch changes boost, diff, and ABS for surface type.' },
      { name: 'Water Injection', desc: 'Mist injection lowers intake temps on long full-throttle pulls.' },
    ],
    technology: [
      { name: 'Surface GPS Mode', desc: 'Auto-detects gravel vs tarmac via accelerometer and switches maps.' },
      { name: 'Pace Note Display', desc: 'Head-up style dash shows next 3 corners from co-driver tablet link.' },
      { name: 'Jump Landing Dampening', desc: 'Rebound auto-softens when airborne detected by G sensor.' },
      { name: 'Snow Chain Quick Mount', desc: 'Hub design allows chain fit in under 8 minutes service halt.' },
    ],
    accel200: 12.8, quarterMile: 12.4,
  },
  {
    id: 'nitro-drag', name: 'Nitro Drag 500', category: 'drag', badge: 'Drag Strip',
    image: 'assets/cars/drag.jpg',
    hp: 1200, speed: 400, accel: 1.6, torque: 1450, weight: 1100,
    engine: '7.0L Supercharged V8', drivetrain: 'RWD', transmission: '2-Speed Powerglide Auto', fuel: 'Nitromethane / Methanol',
    desc: 'Top Fuel-inspired dragster delivering 1,200 HP and 8.2-second quarter-mile with nitrous and parachute recovery.',
    pedigree: 'Teevra Drag Racing · NHRA Pro Modified class · Quarter-mile specialist',
    highlights: ['8.2 sec quarter mile', '1.6s 0–100 km/h', '400+ km/h trap speed', 'Nitrous + supercharger', 'Parachute dual-stage'],
    performance: { power: 100, speed: 99, handling: 55, aero: 70, braking: 75, acceleration: 100, durability: 65, efficiency: 45 },
    engineSpecs: {
      layout: 'V8 Supercharged + nitrous', displacement: '7,000 cc', cylinders: '8',
      compression: '11.5:1', turbo: 'Blower 14-71 roots type', redline: '7,200 RPM',
      powerOutput: '1,200 HP @ 6,500 RPM (+ 200 HP nitrous)', torquePeak: '1,450 Nm @ 5,000 RPM',
      fuelSystem: 'Mechanical injection', cooling: 'Ice tank intercooler + oil cooler',
      hybridSystem: 'None', emissions: 'Open exhaust race use',
    },
    chassisSpecs: {
      frame: 'Chromoly tubular spaceframe', length: '7,200 mm', width: '760 mm',
      height: '1,100 mm', wheelbase: '4,800 mm', trackF: '12 inch front bicycle', trackR: '36 inch slicks',
      suspension: 'Solid front axle / 4-link rear', dampers: 'Adjustable coilover rear only',
      brakes: 'Dual chute + 4-piston rear disc', tires: 'Mickey Thompson 36×17.5 slick rear',
      aero: 'Front narrow body + wheelie bar', weightDist: '35% front / 65% rear',
      fuelTank: '15 L methanol · 1/4 mile per run', safety: 'NHRA chassis cert + 5-point harness',
    },
    featuresDetailed: [
      { name: 'Nitrous Oxide Injection', desc: '200 HP shot on launch controlled by timer and RPM window.' },
      { name: 'Wheelie Bar', desc: 'Adjustable height bars prevent flip on violent 3G launches.' },
      { name: 'Dual Drag Parachute', desc: 'Primary at 320 km/h, secondary at 280 km/h for safe shutdown.' },
      { name: 'Line Lock', desc: 'Front brake lock heats rear slicks for optimal launch grip.' },
      { name: 'Transbrake', desc: 'Reverse solenoid holds car at line with engine at 5,000 RPM.' },
      { name: 'Launch RPM Limiter', desc: 'Two-step rev limiter holds consistent staging RPM.' },
      { name: 'Data Acquisition', desc: '60-foot, 330-foot, and trap speed logged every run.' },
      { name: 'Clutch Slippage Control', desc: 'Centrifugal clutch tuning for varying track grip levels.' },
    ],
    technology: [
      { name: 'Weather Correction Factor', desc: 'ECU adjusts fuel for density altitude and humidity.' },
      { name: 'Blower Overdrive', desc: 'Variable pulley ratio tunes boost from 18–28 psi.' },
      { name: 'Wheel Speed Sensors', desc: 'Detects tire spin and cuts ignition within 20 ms.' },
      { name: 'Parachute Auto-Deploy', desc: 'G-force trigger fires chute if driver fails manual pull.' },
    ],
    accel200: 3.8, quarterMile: 8.2,
  },
  {
    id: 'le-mans', name: 'Le Mans Prototype', category: 'endurance', badge: 'Le Mans',
    image: 'assets/cars/endurance-lambo.jpg',
    hp: 900, speed: 360, accel: 2.5, torque: 920, weight: 1030,
    engine: '5.2L Hybrid V10', drivetrain: 'AWD', transmission: '7-Speed Sequential', fuel: 'Hybrid (E20)',
    desc: 'LMDh prototype with closed cockpit, hybrid boost, and 360 km/h Mulsanne Straight capability for 24-hour Le Mans.',
    pedigree: 'Teevra Endurance · FIA WEC Hypercar class · Le Mans 24H winner platform',
    highlights: ['24-hour race proven', '360 km/h Vmax', 'Hybrid KERS boost', 'Closed cockpit', 'Night LED matrix'],
    performance: { power: 92, speed: 90, handling: 91, aero: 94, braking: 89, acceleration: 90, durability: 95, efficiency: 85 },
    engineSpecs: {
      layout: '90° V10 + front-axle MGU', displacement: '5,204 cc', cylinders: '10',
      compression: '12.0:1', turbo: 'None (NA + hybrid fill)', redline: '9,200 RPM',
      powerOutput: '900 HP combined', torquePeak: '920 Nm @ 6,500 RPM',
      fuelSystem: 'Direct injection 350 bar', cooling: 'Side pod + brake duct cooling',
      hybridSystem: '200 kW front axle deploy', emissions: 'FIA WEC fuel allowance',
    },
    chassisSpecs: {
      frame: 'Carbon LMP monocoque', length: '5,100 mm', width: '2,000 mm',
      height: '1,050 mm', wheelbase: '3,148 mm', trackF: '1,620 mm', trackR: '1,550 mm',
      suspension: 'Double wishbone push-rod', dampers: 'Multimatic four-way',
      brakes: 'Carbon 390 mm / 6-piston', tires: 'Michelin LM slick 31/71-R18',
      aero: 'Full ground effect + adjustable wing', weightDist: '46% front / 54% rear',
      fuelTank: '90 L · ~12 lap stint', safety: 'Closed cockpit + side impact panels',
    },
    featuresDetailed: [
      { name: 'Closed Cockpit', desc: 'Sealed cabin with A/C maintains driver focus over 24-hour stints.' },
      { name: 'Hybrid Energy Store', desc: '200 kW deploy on Mulsanne and out of Arnage for overtakes.' },
      { name: 'Night LED Matrix', desc: 'Homologated headlight pattern for 340 km/h night visibility.' },
      { name: 'Driver Drink System', desc: '1.2 L hydration bottle with bite-valve, refillable at pit stop.' },
      { name: 'Aero Balance Switch', desc: 'Driver adjusts wing angle ±2° for traffic vs clear air.' },
      { name: 'Pit Speed GPS', desc: 'Auto limiter prevents drive-through penalties in pit lane.' },
      { name: 'Brake Duct Modulator', desc: 'Adjusts cooling to prevent overnight brake temperature drop.' },
      { name: 'Stint Timer HUD', desc: 'Shows fuel, tire life, and mandatory driver change countdown.' },
    ],
    technology: [
      { name: 'MGU Front Axle', desc: 'Recovers under braking and deploys for 4WD traction exiting slow corners.' },
      { name: 'Virtual Safety Car Mode', desc: 'Auto fuel-save map when race control neutralizes field.' },
      { name: 'Acoustic Driver Alert', desc: 'Vibration seat warns of faster class cars approaching from rear.' },
      { name: 'Tire IR Monitoring', desc: 'Infrared cameras track surface temp across 24-hour temperature swing.' },
    ],
    accel200: 6.8, quarterMile: 10.2,
  },
  {
    id: 'track-day', name: 'Track Day M-Series', category: 'gt', badge: 'Track Day',
    image: 'assets/cars/track-bmw.jpg',
    hp: 650, speed: 310, accel: 3.1, torque: 680, weight: 1350,
    engine: '3.0L Twin-Turbo I6', drivetrain: 'RWD', transmission: '8-Speed DCT', fuel: '98 Octane',
    desc: 'Club circuit track day special with roll bar, data logging, and fade-free brakes for 20-lap sessions.',
    pedigree: 'Teevra Track Program · BMW M Motorsport derived · Club sport spec',
    highlights: ['Hot-lap telemetry', 'Fade-free brakes', 'Bucket seat + harness', 'Oil cooler std', 'Adjustable dampers'],
    performance: { power: 80, speed: 78, handling: 92, aero: 76, braking: 86, acceleration: 81, durability: 82, efficiency: 70 },
    engineSpecs: {
      layout: 'Inline-6 Twin Turbo', displacement: '2,993 cc', cylinders: '6',
      compression: '10.2:1', turbo: 'Twin-scroll single turbo', redline: '7,200 RPM',
      powerOutput: '650 HP @ 6,500 RPM', torquePeak: '680 Nm @ 3,800 RPM',
      fuelSystem: 'Direct injection', cooling: 'Engine + trans + diff oil coolers',
      hybridSystem: 'None', emissions: 'Track use only',
    },
    chassisSpecs: {
      frame: 'Unibody + welded roll bar', length: '4,550 mm', width: '1,870 mm',
      height: '1,320 mm', wheelbase: '2,741 mm', trackF: '1,580 mm', trackR: '1,560 mm',
      suspension: 'Strut front / multi-link rear', dampers: 'KW Clubsport 3-way',
      brakes: 'Steel 380 mm / 6-piston', tires: 'Michelin Pilot Sport Cup 2 R 265/35-R19',
      aero: 'Front lip + small rear spoiler', weightDist: '52% front / 48% rear',
      fuelTank: '68 L · ~280 km track', safety: 'Roll bar + 6-point harness + HANS',
    },
    featuresDetailed: [
      { name: 'Bucket Seats & Harness', desc: 'Recaro Podium seats with Sabelt 6-point FIA harness.' },
      { name: 'Roll Bar', desc: 'Bolt-in half cage with rear diagonal for track day compliance.' },
      { name: 'AIM Data Logger', desc: 'GPS lap timing, sector splits, and predictive lap delta.' },
      { name: 'Oil Cooler Package', desc: 'Stacked engine and transmission coolers prevent heat soak.' },
      { name: 'Adjustable Dampers', desc: 'Compression and rebound clickers accessible without jacking car.' },
      { name: 'Brake Cooling Ducts', desc: 'Hose-fed front ducts maintain 650°C optimal rotor temp.' },
      { name: 'Fire Extinguisher', desc: 'FIA-compliant 2 kg system mounted within driver reach.' },
      { name: 'Tow Hooks F/R', desc: 'Color-coded hooks for safe recovery without chassis damage.' },
    ],
    technology: [
      { name: 'Hot-Lap Export', desc: 'USB download of full session data for analysis in Race Studio.' },
      { name: 'Brake Pad Wear Sensor', desc: 'Dash warning when pad thickness below 4 mm remaining.' },
      { name: 'Coolant Temp Alert', desc: 'Voice alert when water exceeds 105°C in long sessions.' },
      { name: 'Traction Step Dial', desc: '10-step MDM-style slip control for varying skill levels.' },
    ],
    accel200: 10.4, quarterMile: 11.4,
  },
  {
    id: 'endurance-r', name: 'AMG Endurance R-900', category: 'endurance', badge: 'Endurance',
    image: 'assets/cars/endurance-mercedes.jpg',
    hp: 850, speed: 350, accel: 2.7, torque: 880, weight: 1180,
    engine: '4.0L Hybrid Turbo V8', drivetrain: 'AWD', transmission: '8-Speed AMG Speedshift', fuel: 'Hybrid (E10)',
    desc: 'Mercedes-AMG derived endurance GT with hybrid KERS, night vision HUD, and 12-hour stint reliability.',
    pedigree: 'AMG Customer Racing · IMSA GTD Pro · Daytona 24H contender',
    highlights: ['12-hour stint rated', 'Hybrid torque fill', 'Night vision HUD', 'Air jack pits', '350 km/h Vmax'],
    performance: { power: 90, speed: 88, handling: 87, aero: 90, braking: 91, acceleration: 87, durability: 93, efficiency: 80 },
    engineSpecs: {
      layout: 'Hot-V Twin Turbo V8 + EQ Boost', displacement: '3,982 cc', cylinders: '8',
      compression: '9.0:1', turbo: 'Twin turbo hot-V layout', redline: '7,800 RPM',
      powerOutput: '850 HP combined', torquePeak: '880 Nm @ 5,500 RPM',
      fuelSystem: 'Direct injection + port', cooling: 'Dual charge-air + gearbox cooler',
      hybridSystem: '48V EQ Boost 16 kW', emissions: 'IMSA fuel cell rules',
    },
    chassisSpecs: {
      frame: 'Aluminum spaceframe + steel roll cage', length: '4,780 mm', width: '2,050 mm',
      height: '1,300 mm', wheelbase: '2,800 mm', trackF: '1,670 mm', trackR: '1,630 mm',
      suspension: 'Double wishbone all corners', dampers: 'Öhlins TTX endurance spec',
      brakes: 'Carbon ceramic 400 mm', tires: 'Continental Endurance 300/680-R18',
      aero: 'GT3 spec wing + splitter', weightDist: '47% front / 53% rear',
      fuelTank: '110 L · ~420 km stint', safety: 'FIA endurance roll cage + fuel cell',
    },
    featuresDetailed: [
      { name: 'Hybrid KERS', desc: '48V system adds 160 Nm for 10 seconds per lap under full deploy.' },
      { name: 'Night Vision HUD', desc: 'Infrared overlay highlights track limits and slower traffic at night.' },
      { name: 'Pit Stop Air Jack', desc: 'Onboard compressor lifts car for tire change without external equipment.' },
      { name: 'Fuel-Save Mode', desc: 'ECU map reduces consumption 8% during full-course yellow.' },
      { name: 'Thermal Imaging Camera', desc: 'Rear-facing IR detects overheating traffic before pass attempt.' },
      { name: 'Multi-Map ECU', desc: 'Switch between quali, race, wet, and save maps from steering wheel.' },
      { name: 'Driver Cooling Suit', desc: 'Circulating cool-shirt system integrated with drink bottle chill.' },
      { name: 'Endurance Seat Foam', desc: 'Medical-grade foam reduces driver fatigue over 12-hour stints.' },
    ],
    technology: [
      { name: 'Predictive Pit Strategy', desc: 'AI calculates optimal stop lap based on FCY probability.' },
      { name: 'Tire Stint Modeling', desc: 'Deg curve predicts grip fall-off lap 18–24 of each stint.' },
      { name: 'V2V Race Link', desc: 'Team car proximity alerts prevent same-team blocking incidents.' },
      { name: 'Brake Magic Pedal', desc: 'Rear bias shift button for overtaking under braking into turn 1.' },
    ],
    accel200: 7.6, quarterMile: 10.8,
  },
  {
    id: 'formula-e', name: 'Teevra Formula E', category: 'electric', badge: 'Formula E',
    image: 'assets/cars/model-ev.jpg',
    hp: 550, speed: 280, accel: 2.9, torque: 820, weight: 920,
    engine: 'Dual Motor Electric', drivetrain: 'AWD', transmission: 'Single-Speed Front & Rear', fuel: 'Electric (800V)',
    desc: 'Gen3 Formula E racer with 800V architecture, Attack Mode boost, and 250 kW regenerative braking.',
    pedigree: 'Teevra Electric Racing · FIA Formula E Gen3 · Street circuit champion',
    highlights: ['820 Nm instant torque', 'Attack Mode +50 kW', '250 kW regen', '800V architecture', 'Zero emissions'],
    performance: { power: 82, speed: 75, handling: 89, aero: 88, braking: 85, acceleration: 88, durability: 80, efficiency: 95 },
    engineSpecs: {
      layout: 'Dual motor AWD', displacement: 'N/A (electric)', cylinders: 'N/A',
      compression: 'N/A', turbo: 'N/A', redline: '20,000 RPM (motor)',
      powerOutput: '550 HP (350 kW) race mode', torquePeak: '820 Nm instant',
      fuelSystem: '800V battery 54 kWh', cooling: 'Dielectric battery cooling loop',
      hybridSystem: 'Full electric + regen', emissions: 'Zero tailpipe',
    },
    chassisSpecs: {
      frame: 'Carbon Gen3 monocoque', length: '5,160 mm', width: '1,800 mm',
      height: '1,050 mm', wheelbase: '3,100 mm', trackF: '1,550 mm', trackR: '1,500 mm',
      suspension: 'Double wishbone', dampers: 'Multimatic adaptive',
      brakes: 'Rear regen primary + front disc', tires: 'Hankook iON race 18 inch',
      aero: 'Simplified spec for close racing', weightDist: '48% front / 52% rear',
      fuelTank: '54 kWh · ~45 min + attack', safety: 'Halo + battery crash structure',
    },
    featuresDetailed: [
      { name: '800V Architecture', desc: 'High voltage enables faster charging between sessions and lighter cables.' },
      { name: '250 kW Regen Braking', desc: 'Rear motor recovers energy under braking — no rear friction brakes needed.' },
      { name: 'Attack Mode Boost', desc: 'Temporary +50 kW power when passing through activation zone.' },
      { name: 'Battery Thermal Mgmt', desc: 'Liquid cooling keeps pack between 40–55°C for consistent output.' },
      { name: 'Fan Boost', desc: 'Social voting unlocks extra 25 kW for 30 seconds once per race.' },
      { name: 'Wireless Telemetry', desc: 'Real-time energy consumption displayed to fans and strategists.' },
      { name: 'Power Train Lock', desc: 'FIA seals ensure identical power unit performance across grid.' },
      { name: 'Rain Mode Map', desc: 'Instant torque reduction and stability map for wet street circuits.' },
    ],
    technology: [
      { name: 'Torque Vectoring AWD', desc: 'Independent front/rear motor control rotates car on throttle.' },
      { name: 'Energy Management AI', desc: 'Optimizes regen vs deploy to finish race with 0.1% SOC margin.' },
      { name: 'Fast Charge Pit', desc: '80 kW flash charge adds 10 kWh during full-course yellow.' },
      { name: 'Acoustic Vehicle Alert', desc: 'Synthesized sound warns pedestrians on city street layouts.' },
    ],
    accel200: 8.2, quarterMile: 11.2,
  },
  {
    id: 'hyper-gt', name: 'Hypercar GT-X', category: 'gt', badge: 'Hypercar GT',
    image: 'assets/cars/model-suv.jpg',
    hp: 780, speed: 330, accel: 2.6, torque: 760, weight: 1480,
    engine: '4.5L Twin-Turbo V8', drivetrain: 'AWD', transmission: '8-Speed DCT', fuel: 'Race Fuel 102 RON',
    desc: 'Rallycross-bred GT crossover with adjustable ride height, terrain modes, and AWD torque vectoring.',
    pedigree: 'Teevra Hypercar Division · FIA Rallycross RX1 · Mixed surface specialist',
    highlights: ['Adjustable ride height', 'AWD torque vectoring', 'Rallycross homologated', 'Terrain mode select', '330 km/h Vmax'],
    performance: { power: 86, speed: 84, handling: 85, aero: 78, braking: 84, acceleration: 86, durability: 86, efficiency: 65 },
    engineSpecs: {
      layout: '90° V8 Twin Turbo', displacement: '4,494 cc', cylinders: '8',
      compression: '10.5:1', turbo: 'Twin parallel turbos', redline: '7,400 RPM',
      powerOutput: '780 HP @ 6,800 RPM', torquePeak: '760 Nm @ 4,200 RPM',
      fuelSystem: 'Direct injection', cooling: 'Intercooler + trans cooler',
      hybridSystem: 'None', emissions: 'Race spec',
    },
    chassisSpecs: {
      frame: 'Steel unibody + rally reinforcement', length: '4,720 mm', width: '1,980 mm',
      height: '1,450 mm (adjustable ±80 mm)', wheelbase: '2,850 mm', trackF: '1,640 mm', trackR: '1,640 mm',
      suspension: 'MacPherson + multi-link air-adjust', dampers: 'Reiger rallycross',
      brakes: 'Steel 390 mm / 6-piston', tires: 'Pirelli RX cross-compound 235/650-R19',
      aero: 'Roof spoiler + front dive planes', weightDist: '49% front / 51% rear',
      fuelTank: '75 L · ~260 km mixed', safety: 'FIA RX roll cage + side bars',
    },
    featuresDetailed: [
      { name: 'Adjustable Ride Height', desc: 'Air suspension raises 80 mm for gravel or lowers for tarmac laps.' },
      { name: 'Rallycross Diff', desc: 'Mechanical LSD with ramp angles tuned for loose surface traction.' },
      { name: 'Rear Spoiler', desc: 'Active spoiler adds 120 kg downforce at 200 km/h on tarmac mode.' },
      { name: 'Terrain Mode Select', desc: 'Gravel / tarmac / snow maps adjust boost, diff, and ABS in one dial.' },
      { name: 'Reinforced Subframe', desc: 'Steel skid-mounted subframe absorbs jump landings without flex.' },
      { name: 'Quick-Ratio Steering', desc: '2.4 turns lock-to-lock for tight RX hairpins and Joker laps.' },
      { name: 'Intercooler Water Spray', desc: 'Driver-triggered mist prevents heat soak on repeated hot laps.' },
      { name: 'Launch Control AWD', desc: 'Pre-loads rear diff for maximum grip off dirt start grid.' },
    ],
    technology: [
      { name: 'Torque Vectoring AWD', desc: 'Rear axle splits torque left/right for power-slide control.' },
      { name: 'G-Sensor Jump Mode', desc: 'Softens dampers automatically when airborne over tabletop jumps.' },
      { name: 'Surface Auto-Detect', desc: 'Wheel slip algorithm switches terrain map without driver input.' },
      { name: 'Hybrid RX Ready', desc: 'Chassis pre-wired for 2027 RX2e electric conversion package.' },
    ],
    accel200: 8.8, quarterMile: 10.9,
  },
];
